//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgdiff.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pgdiff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find column &apos;{0}&apos; in table &apos;{1}&apos;.
        /// </summary>
        internal static string CannotFindColumnInTable {
            get {
                return ResourceManager.GetString("CannotFindColumnInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find object &apos;{0}&apos; for statement &apos;{1}&apos;..
        /// </summary>
        internal static string CannotFindObject {
            get {
                return ResourceManager.GetString("CannotFindObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find schema &apos;{0}&apos; for statement &apos;{1}&apos;. Missing CREATE SCHEMA statement?.
        /// </summary>
        internal static string CannotFindSchema {
            get {
                return ResourceManager.GetString("CannotFindSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find sequence &apos;{0}&apos; for statement &apos;{1}&apos;. Missing CREATE SEQUENCE?.
        /// </summary>
        internal static string CannotFindSequence {
            get {
                return ResourceManager.GetString("CannotFindSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find table &apos;{0}&apos; for statement &apos;{1}&apos;. Missing CREATE TABLE?.
        /// </summary>
        internal static string CannotFindTable {
            get {
                return ResourceManager.GetString("CannotFindTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find column &apos;{0}&apos; in table &apos;{1}&apos; for statement &apos;{2}&apos;..
        /// </summary>
        internal static string CannotFindTableColumn {
            get {
                return ResourceManager.GetString("CannotFindTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find view &apos;{0}&apos; for statement &apos;{1}&apos;. Missing CREATE VIEW statement?.
        /// </summary>
        internal static string CannotFindView {
            get {
                return ResourceManager.GetString("CannotFindView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nExpected data type definition at position {1} &apos;{2}&apos;.
        /// </summary>
        internal static string CannotParseStringExpectedDataType {
            get {
                return ResourceManager.GetString("CannotParseStringExpectedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nExpected expression at position {1} &apos;{2}&apos;.
        /// </summary>
        internal static string CannotParseStringExpectedExpression {
            get {
                return ResourceManager.GetString("CannotParseStringExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nExpected integer at position {1} &apos;{2}&apos;.
        /// </summary>
        internal static string CannotParseStringExpectedInteger {
            get {
                return ResourceManager.GetString("CannotParseStringExpectedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nExpected string at position {1}.
        /// </summary>
        internal static string CannotParseStringExpectedString {
            get {
                return ResourceManager.GetString("CannotParseStringExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nExpected {1} at position {2} &apos;{3}&apos;.
        /// </summary>
        internal static string CannotParseStringExpectedWord {
            get {
                return ResourceManager.GetString("CannotParseStringExpectedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse string: {0}\nUnsupported command at position {1} &apos;{2}&apos;.
        /// </summary>
        internal static string CannotParseStringUnsupportedCommand {
            get {
                return ResourceManager.GetString("CannotParseStringUnsupportedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read file.
        /// </summary>
        internal static string CannotReadFile {
            get {
                return ResourceManager.GetString("CannotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find ending semicolon of statement: {0}.
        /// </summary>
        internal static string EndOfStatementNotFound {
            get {
                return ResourceManager.GetString("EndOfStatementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unknown option.
        /// </summary>
        internal static string ErrorUnknownOption {
            get {
                return ResourceManager.GetString("ErrorUnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database ignored statements.
        /// </summary>
        internal static string NewDatabaseIgnoredStatements {
            get {
                return ResourceManager.GetString("NewDatabaseIgnoredStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original database ignored statements.
        /// </summary>
        internal static string OriginalDatabaseIgnoredStatements {
            get {
                return ResourceManager.GetString("OriginalDatabaseIgnoredStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE change - table: {0} original: {1} new: {2}.
        /// </summary>
        internal static string TypeParameterChange {
            get {
                return ResourceManager.GetString("TypeParameterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported encoding.
        /// </summary>
        internal static string UnsupportedEncoding {
            get {
                return ResourceManager.GetString("UnsupportedEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: apgdiff [options] &lt;old_dump&gt; &lt;new_dump&gt;
        ///
        ///Options:
        ///
        ///--version:
        ///	displays apgdiff version
        ///
        ///--add-defaults:
        ///	adds DEFAULT ... in case new column has NOT NULL constraint but no default
        ///	value (the default value is dropped later)
        ///
        ///--add-transaction:
        ///	adds START TRANSACTION and COMMIT TRANSACTION to the generated diff file
        ///
        ///--ignore-function-whitespace:
        ///	ignores multiple spaces and new lines when comparing content of functions
        ///	- WARNING: this may cause functions to appear to be same in cas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsageHelp {
            get {
                return ResourceManager.GetString("UsageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Column {0} in new table has no STORAGE set but in old table storage was set. Unable to determine STORAGE type..
        /// </summary>
        internal static string WarningUnableToDetermineStorageType {
            get {
                return ResourceManager.GetString("WarningUnableToDetermineStorageType", resourceCulture);
            }
        }
    }
}
